version: '3.8'

services:
  database:
    ports:
      - 3307:3306
    build:
      context: .
      dockerfile: Dockerfile-database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: 'Ows1234root'
      MYSQL_DATABASE: 'hive'

  php:
    ports: 
      - 8000:8000
    volumes:
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile-php