# Oude Dockerfile voor Jenkins zonder PHP en PHPunit
# FROM jenkins/jenkins:2.440.1-jdk17
# USER root
# RUN apt-get update && apt-get install -y lsb-release
# RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
#   https://download.docker.com/linux/debian/gpg
# RUN echo "deb [arch=$(dpkg --print-architecture) \
#   signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
#   https://download.docker.com/linux/debian \
#   $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
# RUN apt-get update && apt-get install -y docker-ce-cli
# 
# USER root
# RUN jenkins-plugin-cli --plugins "blueocean docker-workflow" */

FROM jenkins/jenkins:2.440.1-jdk17

USER root

RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli

RUN apt-get update && apt-get install -y \
    php \
    php-cli \
    php-xml \
    php-mbstring \
    wget \
    unzip
RUN wget https://getcomposer.org/installer -O composer-setup.php && \
    php composer-setup.php --install-dir=/usr/local/bin --filename=composer && \
    rm composer-setup.php
RUN composer global require phpunit/phpunit

ENV PATH="/root/.composer/vendor/bin:${PATH}"

RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"